
# https://github.com/LeidyJimenez89/Cacao/

  development:
    adapter: mysql2
    encoding: utf8
    database: nomina_development
    username: root
    password: root
    host: localhost
    port: 3306
